### ISSUE TITLE
ERROR :: net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: No active session with ID

### ISSUE THREAD

**Issue by Renjusc** [serenity-bdd/serenity-maven-plugin#78]
Scripts are failing with the following error. Tried to execute the script locally on chrome and on grid as well. Please advise.

No active session with ID b324bd213592fbdc663589a2beae51da (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 0 millisecondsBuild info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'System info: host: 'V105P10PRA0386', ip: '10.74.36.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'Driver info: org.openqa.selenium.remote.RemoteWebDriverCapabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.41.578700 (2f1ed5f9343c13..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:38959}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 68.0.3440.84, webStorageEnabled: true, webdriver.remote.sessionid: b324bd213592fbdc663589a2bea...}Session ID: b324bd213592fbdc663589a2beae51daFor documentation on this error, please visit: http://seleniumhq.org/exceptionso_such_element.htmlBuild info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z'System info: host: 'V105P10PRA0386', ip: '10.74.36.102', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'Driver info: driver.version: unknown
ERROR :: net.serenitybdd.core.exceptions.SerenityManagedException: The following error occurred: No active session with ID

Everything was working fine since last week. 

Dependency versions that I'm using in my project
<java.version>1.8</java.version>
        
        <surefire.version>2.20.1</surefire.version>
        <failsafe.version>2.20.1</failsafe.version>
        <compiler.version>3.7.0</compiler.version>
        <enforcer.version>3.0.0-M1</enforcer.version>
        <sonar.version>3.3.0.603</sonar.version>

        

        <junit.version>4.12</junit.version>
        <assertj.version>3.8.0</assertj.version>
        <slf4j.version>1.7.21</slf4j.version>
        <serenity.version>1.8.1</serenity.version>
        <serenity.maven.version>1.8.0</serenity.maven.version>
        <serenity.cucumber.version>1.6.5</serenity.cucumber.version>
        <cucumber.jvm.parallel.version>4.2.0</cucumber.jvm.parallel.version>

**Comment by Renjusc** [comment]
Can someone please assist me with this issue?

**Comment by wakaleo** [comment]
If nothing in your code has changed, it's probably a chromedriver issue. Make sure your chromedriver version is compatible with the version of chrome running on the server.

**Comment by SiKing** [comment]
Your chromedriverVersion: 2.41.578700 is from 2018!

Also your Selenium version:  version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:01:39.354Z' is quite outdated.

I'm surprised any of this worked "last week".

**Comment by Renjusc** [comment]
> If nothing in your code has changed, it's probably a chromedriver issue. Make sure your chromedriver version is compatible with the version of chrome running on the server.

On Grid, I'm using chromedriverVersion: 2.41.578700 and browser version  68.0.3440.84 that are compatible.

**Comment by Renjusc** [comment]
Now I'm getting a different error.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.20.1:verify (default) on project stockbrokingfrontend: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\Workspace\bitbucket\stockbroking-website-rewrite-fe\target\failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_161\jre\bin\java" -Xmx512m -XX:MaxPermSize=256m -jar C:\Users\cc313550\AppData\Local\Temp\surefire298783638197738135\surefirebooter8793239549329120048.jar C:\Users\cc313550\AppData\Local\Temp\surefire298783638197738135 2020-09-17T08-17-08_487-jvmRun1 surefire4220924813137996759tmp surefire_04912849175042389701tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] ExecutionException Error occurred in starting fork, check output in log
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_161\jre\bin\java" -Xmx512m -XX:MaxPermSize=256m -jar C:\Users\cc313550\AppData\Local\Temp\surefire298783638197738135\surefirebooter900884534206367567.jar C:\Users\cc313550\AppData\Local\Temp\surefire298783638197738135 2020-09-17T08-17-08_487-jvmRun3 surefire6893390059632152200tmp surefire_1720474345576152590tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:496)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkOnceMultiple(ForkStarter.java:370)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:294)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1124)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:954)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:832)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_161\jre\bin\java" -Xmx512m -XX:MaxPermSize=256m -jar C:\Users\cc313550\AppData\Local\Temp\surefire298783638197738135\surefirebooter900884534206367567.jar C:\Users\cc313550\AppData\Local\Temp\surefire298783638197738135 2020-09-17T08-17-08_487-jvmRun3 surefire6893390059632152200tmp surefire_1720474345576152590tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:686)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:535)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$700(ForkStarter.java:116)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:364)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:344)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ERROR] at java.lang.Thread.run(Thread.java:748)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Process finished with exit code 1
